version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo "Hello" | echo
      - echo Building the Docker image $IMAGE_REPO_NAME:$IMAGE_TAG_$CODEBUILD_RESOLVED_SOURCE_VERSION ...
      - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION  .
      #- echo Scanning with Hadolint...
      #- docker run --rm -i hadolint/hadolint hadolint - < Dockerfile
  post_build:
    commands:
      - env
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - printf '[{"name":"nginx","imageUri":"'$AWS_ACCOUNT_ID'.dkr.ecr.'$AWS_DEFAULT_REGION'.amazonaws.com/'$IMAGE_REPO_NAME':'$CODEBUILD_RESOLVED_SOURCE_VERSION'"}]' > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
