name: Test

on:
  push:
    tags:        
      - '*' 
      
jobs:
  s3Backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r dir.zip .
